### PR TITLE
updating contentful management version

### PR DESCRIPTION
**Pull request by itsjoekent**
There have been several bug fixes in Contentful management since the 3.7.6 release, [one of which](https://github.com/contentful/contentful-management.js/releases/tag/v4.0.2) is required to unblock me

### CODE REVIEW

**Comment by itsjoekent** [comment]
@axe312ger Mind if I tag you on this?

**Comment by axe312ger** [comment]
@itsjoekent no worries :)

Are you using contentful-batch-libs with your own implementation or in combination of our import & export tools?

**Comment by itsjoekent** [comment]
@axe312ger Sorry missed the notification, yep I'm using a combination of the import/export tools

**Comment by axe312ger** [comment]
Alright. So, we won't upgrade the current stable versions of import/export to the latest CMA, since new versions of import/export are already in the pipeline and released as beta versions.

You can download them via `npm install --global contentful-export@next contentful-import@next`

These contain several usability and bug fixes and contain the new CMA SDK version, also.

**Pull request closed without merging**
