### PR TITLE
Feat/payload validation

### PR DESCRIPTION
**Pull request by Khaledgarbaya**
This PR adds payload validation for the entities to be imported based on a JSON schema.
If the one of the entity's payload is invalid it will be removed from the array and it a nice warning will be logged telling the user which field is missing and the entity id if possible.

Why?
- centralize all checks in one pass.

This is still a WIP PR I would like to get your inputs on it and how strict should we go in the schema validation.

### CODE REVIEW

**Comment by zcei** [comment]
> telling the user which field is missing

This would involve a lot of dynamic schema building, as you need to compile a new JSON schema per Content Type to check an Entry against it.

I would probably only check for keys that are required to pass our Management API, e.g. a field in a ContentType needs the `type` property.

While building the migration tooling we used `joi` and even there hit some limitations, so only JSON Schema would be very ambitious if you plan to validate Entries.

I recently found [`superstruct`](https://github.com/ianstormtaylor/superstruct), haven't used it yet, but might a good fit.

**Comment by Khaledgarbaya** [comment]
@zcei I don't want to go crazy with the validation, I will just make sure the keys expected by the transformation pass and by the management api.
stuff like assets without `file` field etc

**Comment by axe312ger** [comment]
I like this idea a lot :)

Superstruct looks pretty nice, also :)

Lets discuss monday :)

**Comment by axe312ger** [comment]
@Khaledgarbaya I guess we can close this in favour of https://github.com/contentful/contentful-import/pull/81?

**Pull request closed without merging**
